### ISSUE TITLE
[BUG] toutes les images ne sont pas affichées

### ISSUE THREAD

**Issue by Doncellup** [Churros98/Plugin-Gallery#3]
En gros la 2e page d'images d'azuriom n'est pas affichée :

Dans le plugin : 
![image](https://user-images.githubusercontent.com/90469321/182963314-d5f4c02b-496b-44b5-9ff5-7465806640e3.png)

Dans l'onglet images d'azuriom : 
![image](https://user-images.githubusercontent.com/90469321/182963377-e394dc60-8357-4064-88d3-d5b5d4dbcca8.png)
![image](https://user-images.githubusercontent.com/90469321/182963404-59d3b24f-06bd-4f3b-ae29-358833a248ed.png)

Si tu peux fix ça c'est cool, en attendant que la nouvelle gestion des images arrive 😋

**Comment by Bossbirdyman51** [comment]
+1 j'ai le même soucis ^^

**Comment by Churros98** [comment]
Je viens de commit une solution [ici]( https://github.com/Churros98/Plugin-Gallery/commit/636f61c8cb21a7e136ead4f4cc7b66f195812493)
J'attend un retour de @Doncellup et j'envoi l'update sur le market d'Azuriom ^^
